### ISSUE TITLE
 Reproducing experimental results.

### ISSUE THREAD

**Issue by lk0429** [Wu0409/DuPL#11]
Hello,author!

1. I have followed your experimental setup and conducted training with train_final_voc.py. Why is there a significant difference between the results in my training log (train.log) and yours? 
Here is my training log file: 
[train.log](https://github.com/user-attachments/files/17892347/train.log)

2. After post-processing with CRF, my final segmentation result is 70.107, which is quite different from the 72.2 result in your Table 2. What could be the issue here? Could you please provide some feasible solutions? 
Here is my evaluation log: 
[eval_seg.log](https://github.com/user-attachments/files/17892358/eval_seg.log)

 Your response would be greatly appreciated!

**Comment by Wu0409** [comment]
Hey, thank you for your interest in our work! 😊

I have reviewed your log files, and the configuration settings appear to be correct. However, the significant performance difference you mentioned seems unusual, as similar issues raised previously typically show a variation of < 1.0. You could try resetting the randomness settings to see if this leads to noticeable variations.

Regarding your second question, the CRF in validation is not strongly related to the environment settings. The performance differences are primarily caused by the issue in (1).

**Comment by Wu0409** [comment]
No further updates.
