### ISSUE TITLE
Reproduction of results

### ISSUE THREAD

**Issue by whb919168848** [Wu0409/DuPL#2]
Hello, author.I followed the author's instructions and the final segmentation result of mIoU was only 64.2% on the VOC val. And the CAM result of mIoU was only 67.1% on the VOC val.
[train.log](https://github.com/Wu0409/DuPL/files/15224625/train.log)
This is my train.log.
Can you provide instructions for all the training steps?

**Comment by whb919168848** [comment]
@Wu0409

**Comment by Wu0409** [comment]
Hey, thank you for your interest in our project! 😊

I noticed in your training log that the total batch size might not be set correctly: `Total GPUs: 1, samples per GPU: 1...`. For the VOC dataset, the appropriate batch size should be 4. Since you are using one GPU, the `samples_per_gpu` should be set to `4`, not `1`. 

I will update the README with information regarding the batch size to help clarify this setting later.

Please feel free to reach out if you have any further questions :)

**Comment by whb919168848** [comment]
Ok,I will try.Thanks.

**Comment by whb919168848** [comment]
Hello, author.I follow your suggestions set the samples_per_gpu to 4. It works but the mIou is not the same as yours.(CAM:72.3(yours:73.5), SEG:71.8(yours:72.2)) on the VOC val.
This is my trainlog.
I find some diffrence in your code, like warmup_iters set 1500 in code(2000 in your paper), weight of seg_loss set 0.2(0.1 in paper).
Could you explain it？
[train.log](https://github.com/Wu0409/DuPL/files/15242920/train.log)
@Wu0409

**Comment by Wu0409** [comment]
I've checked your training log, and it looks like your experiment setup is **correct**. Your reimplemented segmentation score is 71.8%, which is slightly lower (by about 0.4%) than what's reported in the paper. I believe this variation is within an tolerable range, considering the variations in experimental environments.

Regarding the inconsistencies between the code and the paper that you pointed out, in fact, we have revised these details in the conference camera-ready version (not published yet). Please follow the settings specified in the repository for now :)

BTW, you can also try ensemble or model soup for the two student models to check whether it can produce better results (though we did not do it in our paper).

**Comment by Wu0409** [comment]
no further updates.
